
export const THEOLOGICAL_TERMS = [
    // Core Concepts
    'Adoption',
    'Allegory',
    'Amen',
    'Anointing',
    'Antichrist',
    'Apocalypse',
    'Apostasy',
    'Apostle',
    'Ascension',
    'Atonement',
    'Baptism',
    'Blasphemy',
    'Christ',
    'Circumcision',
    'Communion',
    'Confession',
    'Consecration',
    'Conversion',
    'Covenant',
    'Creation',
    'Damnation',
    'Deacon',
    'Decalogue',
    'Disciple',
    'Doxology',
    'Elder',
    'Epistle',
    'Eucharist',
    'Evangelism',
    'Expiation',
    'Faith',
    'Fall of Man',
    'Fellowship',
    'Gentile',
    'Glory',
    'Gospel',
    'Grace',
    'Hallelujah',
    'Hell',
    'Holiness',
    'Hosanna',
    'Intercession',
    'Judgement',
    'Justification',
    'Kingdom of God',
    'Law',
    'Legalism',
    'Liturgy',
    'Logos',
    "Lord's Supper",
    'Love',
    'Manna',
    'Mercy',
    'Messiah',
    'Millennium',
    'Ministry',
    'Miracle',
    'Mystery',
    'New Covenant',
    'Old Covenant',
    'Oracle',
    'Ordinance',
    'Original Sin',
    'Parable',
    'Paraclete',
    'Passover',
    'Pastoral Epistles',
    'Patriarch',
    'Pentateuch',
    'Pharisee',
    'Piety',
    'Predestination',
    'Prophecy',
    'Prophet',
    'Propitiation',
    'Psalms',
    'Rapture',
    'Rebirth',
    'Reconciliation',
    'Redemption',
    'Regeneration',
    'Remnant',
    'Repentance',
    'Resurrection',
    'Revelation',
    'Righteousness',
    'Sabbath',
    'Sacrament',
    'Sacrifice',
    'Sadducee',
    'Salvation',
    'Sanctification',
    'Sanctuary',
    'Sanhedrin',
    'Scribe',
    'Second Coming',
    'Sheol',
    'Sin',
    'Soul',
    'Spirit',
    'Stewardship',
    'Tabernacle',
    'Temple',
    'Ten Commandments',
    'Testament',
    'Tithe',
    'Torah',
    'Transfiguration',
    'Tribulation',
    'Trinity',
    'Type/Typology',
    'Vicarious Atonement',
    'Worship',
    'Wrath',
    'Yahweh',
    'Zealot',

    // Doctrines of God (Theology Proper)
    'Attributes of God',
    'Immutability',
    'Omnipotence',
    'Omnipresence',
    'Omniscience',
    'Providence',
    'Sovereignty',
    'Transcendence',

    // Doctrines of Christ (Christology)
    'Christology',
    'Hypostatic Union',
    'Incarnation',
    'Kenosis',

    // Doctrines of the Holy Spirit (Pneumatology)
    'Pneumatology',

    // Doctrines of the Bible (Bibliology)
    'Apocrypha',
    'Bibliology',
    'Canon',
    'Canon of Scripture',
    'Concordance',
    'Exegesis',
    'Hermeneutics',
    'Inerrancy',
    'Infallibility',
    'Inspiration',
    'Septuagint',

    // Doctrines of Sin (Hamartiology)
    'Hamartiology',
    'Total Depravity',

    // Doctrines of Salvation (Soteriology)
    'Common Grace',
    'Election',
    'Foreknowledge',
    'Free Will',
    'Glorification',
    'Irresistible Grace',
    'Limited Atonement',
    'Lordship Salvation',
    'Perseverance of the Saints',
    'Prevenient Grace',
    'Soteriology',
    'Substitutionary Atonement',
    'Unconditional Election',

    // Doctrines of the Church (Ecclesiology)
    'Ecclesiology',

    // Doctrines of Angels/Demons
    'Angelology',
    'Demonology',
    'Satanology',

    // Doctrines of End Times (Eschatology)
    'Eschatology',

    // Systematic Theology & Philosophical Concepts
    'Antinomianism',
    'Arminianism',
    'Calvinism',
    'Covenant Theology',
    'Deism',
    'Dispensationalism',
    'Dispensation',
    'Imputation',
    'Supralapsarianism',
    'Teleology',
    'Theodicy',

    // Historical Heresies/Views
    'Arianism',
    'Docetism',
    'Gnosticism',
    'Heresy',
    'Modalism',
    'Pelagianism',
    'Semi-Pelagianism',

    // The "Five Solas" of the Reformation
    'Sola Fide',
    'Sola Gratia',
    'Sola Scriptura',
    'Solus Christus',
    'Soli Deo Gloria',
].sort();
