
export const TOOLTIP_DEFINITIONS = {
  LITERARY_GENRE: "The category of biblical writing (e.g., Narrative, Poetry, Law, Prophecy). The genre guides how the passage should be interpreted.",
  NARRATIVE_FLOW: "An analysis of the story elements in a passage, including its setting, characters, plot progression, and the author's storytelling techniques.",
  PASSAGE_OUTLINE: "A structured summary of the passage, highlighting its main points and logical flow to clarify the author's argument or narrative sequence.",
  LITERARY_DEVICES: "Techniques used by the author to create a particular effect (e.g., metaphor, parallelism, chiasmus). Identifying these reveals deeper layers of meaning.",
  FIGURES_OF_SPEECH: "Language used in a non-literal way to create a vivid effect (e.g., metaphor, simile, hyperbole). Identifying these helps to interpret the text as intended by the author.",
  DISCOURSE_ANALYSIS: "Examines how this passage connects to the texts immediately before and after it, revealing its role in the book's larger argument or story.",
  GRAMMATICAL_HIGHLIGHTS: "Focuses on significant grammatical features—like verb tenses, repeated words, or key conjunctions—that impact the passage's meaning.",
  HISTORICAL_CULTURAL: "The specific historical events, cultural norms, and social situations of the original author and audience that are essential for understanding the text's intended meaning.",
  ORIGINAL_AUDIENCE: "An analysis of who the text was first written for. Understanding their circumstances helps clarify why the author wrote in a particular way.",
  AUTHORIAL_INTENT: "The likely purpose or message the original author intended to communicate to their specific audience.",
  CANONICAL_CONTEXT: "Examines the passage's role and placement within its book and the entire Bible, connecting it to the overarching biblical storyline.",
  THEMATIC_CONNECTIONS: "Identifies how the passage relates to major, recurring biblical themes such as Covenant, Redemption, Kingdom of God, and Creation.",
  LEXICAL_ORIGINAL: "The word as it appears in the original Hebrew (Old Testament) or Greek (New Testament) text.",
  LEXICAL_TRANSLITERATION: "The pronunciation of the original word using English letters.",
  LEXICAL_STRONGS: "A unique number from Strong's Concordance used to identify the specific original word for cross-referencing and study.",
  LEXICAL_GRAMMAR: "The grammatical form (e.g., noun, verb tense, mood, voice), which affects how the action or state is described.",
  LEXICAL_MEANING: "The definition of the original word, including its nuances and usage in this specific context.",
  LEXICAL_TRANSLATION_JOURNEY: "This section explains how the original Greek or Hebrew word is translated into modern English. It may include notes on its etymology, range of meaning, and any nuances that are gained or lost in translation.",
  COMMENTARY_BOOK_SUMMARY: "A brief overview of the book's main themes, purpose, and structure, providing context for the passage.",
  COMMENTARY_CHAPTER_CONTEXT: "Summarizes the events or arguments in the immediate chapter to situate the selected passage within its local context.",
  COMMENTARY_PASSAGE: "A detailed, verse-by-verse explanation of the passage, clarifying meaning, theological points, and connections.",
  COMMENTARY_PERSPECTIVES: "An exploration of various historical and theological viewpoints on the passage from different Christian traditions.",
  COMMENTARY_APPLICATION: "Practical insights on how the passage's truths can be applied to contemporary life and faith.",
  COMMENTARY_DEVOTIONAL: "A short, reflective thought designed to encourage personal meditation and spiritual growth based on the passage.",
  COMMENTARY_SOURCES_WEB: "A list of web-based sources used by the AI, providing links for further verification and study.",
  COMMENTARY_SOURCES_CONCEPTUAL: "A list of key scholarly commentaries, books, and theological resources that informed the AI's analysis.",
  HARMONY_COMPARISON: "A comparison of this Gospel account with parallel passages in other Gospels, highlighting similarities and differences in wording and detail.",
  HARMONY_UNIQUE: "An analysis of the details, events, or teachings that are unique to this specific Gospel's version of the story.",
  HARMONY_PARALLELS: "A list of direct parallel accounts in other Gospel books. Clicking these will allow for quick comparison.",
  TEXTUAL_RELIABILITY: "An assessment of the manuscript evidence for this passage, discussing the general reliability and confidence scholars have in the text.",
  TEXTUAL_VARIANTS: "Notes significant differences in wording found among ancient manuscripts. This helps understand how the text has been transmitted.",
  EPISTOLARY_ARGUMENT: "An outline of the logical flow and rhetorical structure of the author's argument in the letter.",
  EPISTOLARY_DOCTRINES: "Identifies the key theological teachings or doctrines that are developed or defended in this section of the epistle.",
  EPISTOLARY_APPLICATION: "Discusses the intended practical impact or action the author wanted to see in the original audience of the letter.",
  
  // Thematic Analysis Tooltips
  THEMATIC_SUMMARY: "A concise definition of the topic in its biblical context and an explanation of its overall theological significance.",
  THEMATIC_KEYWORDS: "A brief lexical study of the primary Hebrew and Greek words related to this theme. This provides insight into the original language nuances behind the English terms.",
  THEMATIC_HISTORICAL: "The historical and cultural background that shaped the understanding and expression of this theme in the Bible.",
  THEMATIC_DEVELOPMENT: "Traces how the understanding of this theme unfolds and matures from its origins in the Old Testament to its fulfillment in the New Testament.",
  THEMATIC_CHRISTOLOGICAL: "Explains how the theme is ultimately fulfilled in, points toward, or finds its deepest meaning in the person and work of Jesus Christ. This connects the entire Bible's story to its central figure.",
  THEMATIC_CREEDAL: "Traces the historical understanding of the topic through the early church creeds (like the Nicene Creed) and major Reformation confessions, showing how the church has formally defined this doctrine over centuries.",
  THEMATIC_PERSPECTIVES: "A summary of different major orthodox Christian viewpoints on the topic, promoting a balanced and nuanced understanding.",
  THEMATIC_MISCONCEPTIONS: "Identifies common errors or misunderstandings related to the topic and provides clear, scripturally-grounded corrections.",
  THEMATIC_CONCEPTS: "Definitions of core theological ideas that are essential for a deeper understanding of the main topic. Click to explore.",
  THEMATIC_APPLICATION: "Practical suggestions for how the truths of this theme can be applied to a modern believer's life, faith, and actions.",
  THEMATIC_RELATED: "Other major biblical themes that are closely interconnected with this topic. Click to explore.",
  THEMATIC_VERSES: "A curated list of foundational Bible verses that define, illustrate, or explain the topic.",

  // Q&A Tooltips
  QA_PRINCIPLES: "Core, undisputed biblical truths that form the foundation for the answer, helping to understand the 'why' behind the 'what'.",
  QA_ANSWER: "A direct, context-aware answer to the user's question, grounded in and supported by Scripture.",
  QA_CONTRADICTIONS: "Proactively identifies well-known Bible passages that *seem* to conflict with the answer and provides a concise explanation of how they harmonize with the broader biblical context.",
  QA_HISTORICAL: "The historical and cultural background necessary to properly understand the context of the question and its biblical answer.",
  QA_PERSPECTIVES: "A summary of different major theological viewpoints or interpretations related to the question, providing a balanced and nuanced overview.",
  QA_CONCEPTS: "Definitions of key theological concepts that are central to understanding the answer. Click to explore.",
  QA_REFLECTION: "A set of thought-provoking questions designed to encourage personal meditation and application of the answer's truths.",
  QA_VERSES: "A list of key Bible verses that directly support or illustrate the provided answer.",

  // Parable/Story Tooltips
  PARABLE_TEXT: "The full text of the biblical narrative or parable from the New King James Version (NKJV).",
  PARABLE_SUMMARY: "A concise overview of the story's plot, characters, and main events from beginning to end.",
  PARABLE_CHARACTERS: "An analysis of the key characters, groups, or objects in the story and their symbolic meaning or role in the narrative.",
  PARABLE_CONTEXT: "The specific historical, cultural, and situational setting that provides crucial background for understanding the story's meaning and impact.",
  PARABLE_AUDIENCE: "An explanation of how the story would have been heard and understood by its original audience, anchoring the interpretation in its intended context to prevent modern misreadings.",
  PARABLE_MESSAGE: "The central spiritual lesson, moral, or theological truth that the story is intended to teach, often split into a primary message and secondary themes.",
  PARABLE_WORDS: "A lexical study of the most theologically significant words from the passage in their original language.",
  PARABLE_VERSES: "A list of other Bible verses that are thematically connected to the message or elements of the story.",
  PARABLE_REFLECTION: "A set of thought-provoking questions to help apply the lessons of the story to personal life and faith.",
};

export const LITERARY_DEVICE_DEFINITIONS: Record<string, string> = {
  'Alliteration': 'The repetition of the same sound at the beginning of adjacent or closely connected words (e.g., "The soul that sinneth, it shall die").',
  'Anaphora': 'The repetition of a word or phrase at the beginning of successive clauses for emphasis (e.g., "Blessed are the poor in spirit... Blessed are those who mourn...").',
  'Anthropomorphism': 'Describing God in human terms or with human characteristics to make Him more relatable (e.g., "the arm of the Lord").',
  'Antithesis': 'The juxtaposition of contrasting ideas in balanced phrases or clauses (e.g., "The wicked flee when no one pursues, but the righteous are bold as a lion").',
  'Apostrophe': 'A direct address to an absent person, an inanimate object, or an abstract idea as if it were present and could respond (e.g., "O death, where is your sting?").',
  'Assonance': 'The repetition of vowel sounds within nearby words (e.g., "Hear, O Israel").',
  'Asyndeton': 'The omission of conjunctions (like "and" or "but") between coordinate phrases, clauses, or words to create a hurried rhythm (e.g., "I came, I saw, I conquered").',
  'Chiasmus': 'A literary structure in which concepts or grammatical structures are repeated in reverse order (A-B-B-A pattern) to highlight a central point.',
  'Climax': 'Arranging words, phrases, or clauses in an order of increasing importance or intensity.',
  'Consonance': 'The repetition of consonant sounds within nearby words, especially at the end of stressed syllables (e.g., "strong and willing").',
  'Euphemism': 'A mild or indirect word or expression substituted for one considered to be too harsh or blunt (e.g., "he fell asleep" for "he died").',
  'Hyperbole': 'Intentional exaggeration for emphasis or effect, not meant to be taken literally (e.g., "I cried a river of tears").',
  'Imagery': 'Language that appeals to the senses (sight, sound, smell, touch, taste) to create a vivid picture in the reader\'s mind.',
  'Inclusio': 'A literary device that frames a passage by repeating a word, phrase, or theme at the beginning and end.',
  'Irony': 'A contrast between what is said and what is actually meant (verbal irony), or between what is expected to happen and what really happens (situational irony).',
  'Juxtaposition': 'Placing two concepts, characters, or ideas side-by-side to highlight their differences or similarities.',
  'Litotes': 'An ironic understatement in which an affirmative is expressed by the negative of its contrary (e.g., "not a few" to mean "many").',
  'Merism': 'A figure of speech where two contrasting parts are used to refer to a whole (e.g., "the heavens and the earth" to mean all of creation).',
  'Metaphor': 'A direct comparison between two unlike things, stating that one thing *is* another (e.g., "The Lord is my shepherd").',
  'Metonymy': 'A figure of speech in which a thing or concept is referred to by the name of something closely associated with it (e.g., "the crown" for the king).',
  'Oxymoron': 'A figure of speech in which apparently contradictory terms appear in conjunction (e.g., "living dead").',
  'Paradox': 'A statement that appears self-contradictory but contains a deeper truth (e.g., "Whoever loses their life for my sake will find it").',
  'Parallelism': 'The use of similar grammatical structures, phrases, or clauses in succession to create balance and emphasize ideas.',
  'Personification': 'Giving human qualities or abilities to inanimate objects or abstract ideas (e.g., "the mountains skipped like rams").',
  'Polysyndeton': 'The use of several conjunctions in close succession, especially where some might be omitted, to slow the rhythm (e.g., "We have ships and men and money and stores").',
  'Pun': 'A play on words that have similar sounds but different meanings.',
  'Repetition': 'Repeating a word or phrase to emphasize a point or create a memorable rhythm.',
  'Rhetorical Question': 'A question asked not to receive an answer, but to make a point or create a dramatic effect.',
  'Simile': 'A comparison between two unlike things using "like" or "as" (e.g., "his face shone like the sun").',
  'Symbolism': 'The use of objects, people, or events to represent abstract ideas or concepts.',
  'Synecdoche': 'A figure of speech where a part represents the whole, or the whole represents a part (e.g., "flesh and blood" for a human being).',
  'Theophany': 'A visible manifestation of God to humankind.',
  'Typology': 'The study of biblical "types"—people, events, or institutions in the Old Testament that prefigure a greater reality (the "antitype") in the New Testament.',
  'Wordplay': 'The clever and witty use of words and their meanings, often involving puns.',
  'Zoomorphism': 'Applying animal characteristics to humans or gods.'
};