

import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, Footer, PageNumber, AlignmentType } from 'docx';
import type { VerseAnalysis, ThematicAnalysis, QaAnalysis, EventAnalysis, SystematicAnalysis, ChatMessage, AnalysisResult, AnalysisMode, WordAnalysisItem, StudyStep } from '../types';
import { getStudyTitle } from '../utils/generateStudyKey';

// Helper to save the document by creating a temporary link and clicking it
const saveBlob = (blob: Blob, fileName: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};


// Define styles once to be reused across document generation functions
const documentStyles = {
    paragraphStyles: [
        {
            id: "Heading1",
            name: "Heading 1",
            basedOn: "Normal",
            next: "Normal",
            quickFormat: true,
            run: { size: 36, bold: true, color: "2E74B5" },
            paragraph: { spacing: { before: 240, after: 240 } },
        },
        {
            id: "Heading2",
            name: "Heading 2",
            basedOn: "Normal",
            next: "Normal",
            quickFormat: true,
            run: { size: 32, bold: true, color: "548DD4" },
            paragraph: { spacing: { before: 360, after: 120 } },
        },
        {
            id: "Heading3",
            name: "Heading 3",
            basedOn: "Normal",
            next: "Normal",
            quickFormat: true,
            run: { size: 24, bold: true },
            paragraph: { spacing: { before: 240, after: 60 } },
        },
    ],
};

const defaultFooter = new Footer({
    children: [
        new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
                new TextRun({
                    children: ["Page ", PageNumber.CURRENT, " of ", PageNumber.TOTAL_PAGES],
                    size: 18,
                    italics: true,
                }),
            ],
        }),
        new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
                new TextRun({ text: "Generated by Biblical Insights AI", size: 18, italics: true }),
            ],
        }),
    ],
});

export const exportSingleChatMessageToDocx = (subject: string, message: ChatMessage) => {
    const children: Paragraph[] = [
        new Paragraph({ text: `Chat: ${subject}`, heading: HeadingLevel.HEADING_1 }),
        new Paragraph({ text: `Response from AI`, heading: HeadingLevel.HEADING_3 }),
    ];

    message.text.split('\n').forEach(line => {
        if (line.trim() === '') {
            children.push(new Paragraph(""));
        } else {
            // Simple markdown parsing for bold and italics
            const parts = line.split(/(\*\*.*?\*\*|\*.*?\*)/g).filter(Boolean);
            const textRuns = parts.map(part => {
                if (part.startsWith('**') && part.endsWith('**')) {
                    return new TextRun({ text: part.substring(2, part.length - 2), bold: true });
                }
                if (part.startsWith('*') && part.endsWith('*')) {
                    return new TextRun({ text: part.substring(1, part.length - 1), italics: true });
                }
                return new TextRun(part);
            });
            children.push(new Paragraph({ children: textRuns }));
        }
    });

    const doc = new Document({
        styles: documentStyles,
        sections: [{
            footers: { default: defaultFooter },
            children: children,
        }],
    });
    
    const safeSubject = subject.substring(0, 30).replace(/[\\/:"*?<>|]/g, '');
    const fileName = `Chat_Response_-_${safeSubject}`.replace(/\s/g, '_');
    Packer.toBlob(doc).then(blob => saveBlob(blob, `${fileName}.docx`));
};


// Generates the document structure for a verse analysis
const generateVerseAnalysisDoc = (analysis: VerseAnalysis, reference: { book: string, chapter: number, startVerse: number, endVerse: number }): Document => {
    const referenceString = reference.startVerse === reference.endVerse 
        ? `${reference.book} ${reference.chapter}:${reference.startVerse}` 
        : `${reference.book} ${reference.chapter}:${reference.startVerse}-${reference.endVerse}`;
        
    const children: (Paragraph | Table)[] = [
        new Paragraph({ text: `Biblical Insights AI Analysis`, heading: HeadingLevel.HEADING_1, alignment: AlignmentType.CENTER }),
        new Paragraph({ text: referenceString, heading: HeadingLevel.HEADING_2, alignment: AlignmentType.CENTER }),
    ];

    // Translations Section
    if (analysis.verseText?.KJV) {
        children.push(new Paragraph({ text: "Passage Text", heading: HeadingLevel.HEADING_2 }));
        children.push(new Paragraph({
            children: [
                new TextRun({ text: `KJV: `, bold: true }),
                new TextRun({ text: `"${analysis.verseText.KJV}"`, italics: true }),
            ],
            spacing: { after: 120 }
        }));
    }

    // Key Connections Section
    if (analysis.connections && analysis.connections.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Key Connections", heading: HeadingLevel.HEADING_2 }));
        analysis.connections.forEach(conn => {
            children.push(new Paragraph({
                children: [ new TextRun({ text: `${conn.type}: ${conn.title}`, bold: true }) ],
                spacing: { after: 60 }
            }));
            children.push(new Paragraph({ text: conn.description, bullet: { level: 0 }, indent: { left: 720 }, spacing: { after: 120 } }));
        });
    }

    // Word Analysis Section
    if (analysis.wordAnalysis && analysis.wordAnalysis.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Key Word Analysis", heading: HeadingLevel.HEADING_2 }));
        analysis.wordAnalysis.forEach(word => {
            children.push(
                new Paragraph({ children: [new TextRun({ text: word.word, bold: true, size: 28 })], spacing: { after: 120, before: 240 } }),
                new Paragraph({ children: [ new TextRun({ text: "Original: ", bold: true }), new TextRun({ text: `${word.original} (` }), new TextRun({ text: word.transliteration, italics: true }), new TextRun({ text: ")" })], bullet: { level: 0 }, indent: { left: 720 }, spacing: { after: 60 } }),
                new Paragraph({ children: [ new TextRun({ text: "Strong's: ", bold: true }), new TextRun(word.strongs)], bullet: { level: 0 }, indent: { left: 720 }, spacing: { after: 60 } }),
                new Paragraph({ children: [ new TextRun({ text: "Grammar: ", bold: true }), new TextRun(word.grammar)], bullet: { level: 0 }, indent: { left: 720 }, spacing: { after: 60 } }),
                new Paragraph({ children: [ new TextRun({ text: "Meaning: ", bold: true }), new TextRun(word.meaning)], bullet: { level: 0 }, indent: { left: 720 }, spacing: { after: 60 } }),
            );
        });
    }

    // Structural Analysis Section
    if (analysis.structuralAnalysis) {
        const { literaryGenre, literaryDevices, passageOutline, discourseAnalysis, grammaticalHighlights } = analysis.structuralAnalysis;
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Structural Analysis", heading: HeadingLevel.HEADING_2 }));
        
        children.push(new Paragraph({ text: "Literary Genre", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: literaryGenre.content, spacing: { after: 60 } }));
        children.push(new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true, italics: true }), new TextRun({ text: literaryGenre.relevance, italics: true })], spacing: { after: 120 } }));

        children.push(new Paragraph({ text: "Literary Devices", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: literaryDevices.items.join(', '), spacing: { after: 60 } }));
        children.push(new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true, italics: true }), new TextRun({ text: literaryDevices.relevance, italics: true })], spacing: { after: 120 } }));

        children.push(new Paragraph({ text: "Passage Outline", heading: HeadingLevel.HEADING_3 }));
        passageOutline.items.forEach(item => children.push(new Paragraph({ children: [new TextRun({ text: `${item.verses}: `, bold: true }), new TextRun(item.point)], bullet: { level: 0 }, spacing: { after: 60 } })));
        children.push(new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true, italics: true }), new TextRun({ text: passageOutline.relevance, italics: true })], spacing: { after: 120 } }));

        children.push(new Paragraph({ text: "Discourse Analysis", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: discourseAnalysis.content, spacing: { after: 60 } }));
        children.push(new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true, italics: true }), new TextRun({ text: discourseAnalysis.relevance, italics: true })], spacing: { after: 120 } }));

        children.push(new Paragraph({ text: "Grammatical Highlights", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: grammaticalHighlights.content, spacing: { after: 60 } }));
        children.push(new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true, italics: true }), new TextRun({ text: grammaticalHighlights.relevance, italics: true })], spacing: { after: 120 } }));
    }

    // Context Analysis Section
    if (analysis.contextAnalysis) {
        const { historicalAndCultural, originalAudience, authorialIntent, canonicalContext, thematicConnections } = analysis.contextAnalysis;
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Context & Intent", heading: HeadingLevel.HEADING_2 }));
        
        children.push(new Paragraph({ text: "Historical & Cultural Context", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: historicalAndCultural.content, spacing: { after: 60 } }));
        children.push(new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true, italics: true }), new TextRun({ text: historicalAndCultural.relevance, italics: true })], spacing: { after: 120 } }));

        children.push(new Paragraph({ text: "Original Audience", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: originalAudience.content, spacing: { after: 60 } }));
        children.push(new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true, italics: true }), new TextRun({ text: originalAudience.relevance, italics: true })], spacing: { after: 120 } }));

        children.push(new Paragraph({ text: "Authorial Intent", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: authorialIntent.content, spacing: { after: 60 } }));
        children.push(new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true, italics: true }), new TextRun({ text: authorialIntent.relevance, italics: true })], spacing: { after: 120 } }));

        children.push(new Paragraph({ text: "Canonical Context", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: canonicalContext.content, spacing: { after: 60 } }));
        children.push(new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true, italics: true }), new TextRun({ text: canonicalContext.relevance, italics: true })], spacing: { after: 120 } }));

        children.push(new Paragraph({ text: "Thematic Connections", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: thematicConnections.content, spacing: { after: 60 } }));
        children.push(new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true, italics: true }), new TextRun({ text: thematicConnections.relevance, italics: true })], spacing: { after: 120 } }));
    }

    // Commentary Analysis Section
    if (analysis.commentaryAnalysis) {
        const { bookSummary, chapterContext, passageCommentary, theologicalPerspectives, practicalApplication, devotionalThought, sources } = analysis.commentaryAnalysis;
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Commentary", heading: HeadingLevel.HEADING_2 }));
        children.push(new Paragraph({ text: "Book Summary & Context", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: bookSummary, spacing: { after: 120 } }));
        children.push(new Paragraph({ text: "Chapter Context", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: chapterContext, spacing: { after: 120 } }));
        children.push(new Paragraph({ text: "Passage Commentary", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: passageCommentary, spacing: { after: 120 } }));
        if (theologicalPerspectives?.length > 0) {
            children.push(new Paragraph({ text: "Theological Perspectives", heading: HeadingLevel.HEADING_3 }));
            theologicalPerspectives.forEach(p => children.push(new Paragraph({ children: [new TextRun({ text: `${p.viewpoint}: `, bold: true }), new TextRun(p.description)], spacing: { after: 120 } })));
        }
        if (practicalApplication?.length > 0) {
            children.push(new Paragraph({ text: "Practical Application", heading: HeadingLevel.HEADING_3 }));
            practicalApplication.forEach(point => children.push(new Paragraph({ text: point, bullet: { level: 0 }, spacing: { after: 60 } })));
        }
        if (devotionalThought) {
            children.push(new Paragraph({ text: "Devotional Insight", heading: HeadingLevel.HEADING_3 }));
            children.push(new Paragraph({ children: [new TextRun({ text: `"${devotionalThought}"`, italics: true })], spacing: { after: 120 } }));
        }
        if (analysis.groundingMetadata?.groundingChunks.length > 0) {
            children.push(new Paragraph({ text: "Verifiable Sources (Web)", heading: HeadingLevel.HEADING_3 }));
            analysis.groundingMetadata.groundingChunks.forEach(chunk => children.push(new Paragraph({ text: `${chunk.web.title} (${chunk.web.uri})`, bullet: { level: 0 }, spacing: { after: 60 } })));
        }
        if (sources?.length > 0) {
            children.push(new Paragraph({ text: "Sources Synthesized (Conceptual)", heading: HeadingLevel.HEADING_3 }));
            sources.forEach(source => children.push(new Paragraph({ text: source.name, bullet: { level: 0 }, spacing: { after: 60 } })));
        }
    }

    // Cross References Section
    if (analysis.crossReferenceAnalysis && analysis.crossReferenceAnalysis.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Cross-References", heading: HeadingLevel.HEADING_2 }));
        analysis.crossReferenceAnalysis.forEach(ref => {
            children.push(
                new Paragraph({ text: ref.reference, heading: HeadingLevel.HEADING_3 }),
                new Paragraph({ children: [new TextRun({ text: `"${ref.verseText}"`, italics: true })], indent: { left: 720 } }),
                new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true }), new TextRun(ref.explanation)], spacing: { after: 240 } }),
            );
        });
    }

    // Story Arc Connection
    if (analysis.storyArcConnection) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Story Arc Connection", heading: HeadingLevel.HEADING_2 }));
        children.push(new Paragraph({ text: analysis.storyArcConnection.name, heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: analysis.storyArcConnection.relevance, spacing: { after: 240 } }));
    }

    // Gospel Harmony
    if (analysis.gospelHarmony?.isGospel) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Gospel Harmony", heading: HeadingLevel.HEADING_2 }));
        children.push(new Paragraph({ text: "Synoptic Comparison", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: analysis.gospelHarmony.synopticComparison, spacing: { after: 120 } }));
        children.push(new Paragraph({ text: "Unique Features", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: analysis.gospelHarmony.uniqueFeatures, spacing: { after: 120 } }));
        if (analysis.gospelHarmony.parallels.length > 0) {
            children.push(new Paragraph({ text: "Parallel Accounts", heading: HeadingLevel.HEADING_3 }));
            analysis.gospelHarmony.parallels.forEach(p => children.push(new Paragraph({ children: [new TextRun({ text: `${p.reference}: `, bold: true }), new TextRun({ text: `"${p.text}"`, italics: true })], bullet: { level: 0 }, spacing: { after: 60 } })));
        }
    }

    // Textual Criticism
    if (analysis.textualCriticism?.hasVariants) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Textual Criticism", heading: HeadingLevel.HEADING_2 }));
        children.push(new Paragraph({ text: "Manuscript Reliability", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: analysis.textualCriticism.manuscriptReliability, spacing: { after: 120 } }));
        if(analysis.textualCriticism.variants.length > 0) {
            children.push(new Paragraph({ text: "Variants", heading: HeadingLevel.HEADING_3 }));
            analysis.textualCriticism.variants.forEach(v => {
                children.push(new Paragraph({ text: `Verse: ${v.verse}`, bold: true, spacing: { before: 120 } }));
                children.push(new Paragraph({ children: [new TextRun({ text: 'Variant: ', bold: true }), new TextRun({ text: `"${v.variantText}"`, italics: true })] }));
                children.push(new Paragraph({ children: [new TextRun({ text: 'Manuscripts: ', bold: true }), new TextRun(v.manuscripts)] }));
                children.push(new Paragraph({ children: [new TextRun({ text: 'Significance: ', bold: true }), new TextRun(v.significance)], spacing: { after: 60 } }));
            });
        }
    }

    // Proverbial Connections
    if (analysis.proverbialConnections && analysis.proverbialConnections.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Proverbial Connections", heading: HeadingLevel.HEADING_2 }));
        analysis.proverbialConnections.forEach(conn => children.push( new Paragraph({ text: conn.reference, heading: HeadingLevel.HEADING_3 }), new Paragraph({ children: [new TextRun({ text: `"${conn.verseText}"`, italics: true })], indent: { left: 720 } }), new Paragraph({ children: [new TextRun({ text: "Connection: ", bold: true }), new TextRun(conn.connection)], spacing: { after: 240 } })));
    }

    // Prophetic Fulfillment
    if (analysis.propheticFulfillment && analysis.propheticFulfillment.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Prophetic Fulfillment", heading: HeadingLevel.HEADING_2 }));
        analysis.propheticFulfillment.forEach(item => children.push( new Paragraph({ text: `${item.reference} (${item.type})`, heading: HeadingLevel.HEADING_3 }), new Paragraph({ children: [new TextRun({ text: `"${item.verseText}"`, italics: true })], indent: { left: 720 } }), new Paragraph({ children: [new TextRun({ text: "Explanation: ", bold: true }), new TextRun(item.explanation)], spacing: { after: 240 } })));
    }

    // Covenantal Analysis
    if (analysis.covenantalAnalysis?.hasCovenantLink && analysis.covenantalAnalysis.links.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Covenantal Links", heading: HeadingLevel.HEADING_2 }));
        analysis.covenantalAnalysis.links.forEach(link => {
            children.push(new Paragraph({ text: link.covenant, heading: HeadingLevel.HEADING_3 }));
            children.push(new Paragraph({ children: [new TextRun({ text: "Connection: ", bold: true }), new TextRun(link.connection)], spacing: { after: 60 } }));
            children.push(new Paragraph({ children: [new TextRun({ text: "Significance: ", bold: true }), new TextRun(link.significance)], spacing: { after: 240 } }));
        });
    }

    // Historical Character Analysis
    if (analysis.historicalCharacterAnalysis?.hasCharacters && analysis.historicalCharacterAnalysis.characters.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Key Historical Figures", heading: HeadingLevel.HEADING_2 }));
        analysis.historicalCharacterAnalysis.characters.forEach(char => {
            children.push(new Paragraph({ text: `${char.name} (${char.role})`, heading: HeadingLevel.HEADING_3 }));
            children.push(new Paragraph({ children: [new TextRun({ text: "Significance: ", bold: true }), new TextRun(char.significance)], spacing: { after: 240 } }));
        });
    }

    // Epistolary Analysis
    if (analysis.epistolaryAnalysis?.isEpistle) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Epistolary Analysis", heading: HeadingLevel.HEADING_2 }));
        children.push(new Paragraph({ text: "Argument Structure", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: analysis.epistolaryAnalysis.argumentStructure, spacing: { after: 120 } }));
        children.push(new Paragraph({ text: "Key Doctrines", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: analysis.epistolaryAnalysis.keyDoctrines.join(', '), spacing: { after: 120 } }));
        children.push(new Paragraph({ text: "Original Application", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: analysis.epistolaryAnalysis.originalApplication, spacing: { after: 240 } }));
    }

    // Symbolism Analysis
    if (analysis.symbolismAnalysis?.hasSymbols && analysis.symbolismAnalysis.symbols.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Symbolism", heading: HeadingLevel.HEADING_2 }));
        analysis.symbolismAnalysis.symbols.forEach(item => {
            children.push(new Paragraph({ text: item.symbol, heading: HeadingLevel.HEADING_3 }));
            children.push(new Paragraph({ children: [new TextRun({ text: "Meaning: ", bold: true }), new TextRun(item.meaning)], spacing: { after: 60 } }));
            children.push(new Paragraph({ children: [new TextRun({ text: "Significance: ", bold: true }), new TextRun(item.significance)], spacing: { after: 240 } }));
        });
    }

    // Typology Analysis
    if (analysis.typologyAnalysis?.hasTypology && analysis.typologyAnalysis.connections.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Typology", heading: HeadingLevel.HEADING_2 }));
        analysis.typologyAnalysis.connections.forEach(item => {
            children.push(new Paragraph({ text: `${item.type} → ${item.antitype}`, heading: HeadingLevel.HEADING_3 }));
            children.push(new Paragraph({ children: [new TextRun({ text: "Explanation: ", bold: true }), new TextRun(item.explanation)], spacing: { after: 240 } }));
        });
    }

    // Apocalyptic Symbolism
    if (analysis.apocalypticSymbolism?.hasSymbols && analysis.apocalypticSymbolism.symbols.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Apocalyptic Symbolism", heading: HeadingLevel.HEADING_2 }));
        analysis.apocalypticSymbolism.symbols.forEach(item => {
            children.push(new Paragraph({ text: item.symbol, heading: HeadingLevel.HEADING_3 }));
            children.push(new Paragraph({ children: [new TextRun({ text: "OT Background: ", bold: true }), new TextRun(item.otBackground)], spacing: { after: 60 } }));
            children.push(new Paragraph({ children: [new TextRun({ text: "Symbolic Meaning: ", bold: true }), new TextRun(item.symbolicMeaning)], spacing: { after: 60 } }));
            if (item.crossReferences.length > 0) {
                children.push(new Paragraph({ children: [new TextRun({ text: "Cross-References: ", bold: true }), new TextRun(item.crossReferences.join(', '))], spacing: { after: 240 } }));
            }
        });
    }

    return new Document({
        styles: documentStyles,
        sections: [{
            footers: { default: defaultFooter },
            children: children,
        }],
    });
}

export const exportVerseAnalysisToDocx = (analysis: VerseAnalysis, reference: { book: string, chapter: number, startVerse: number, endVerse: number }) => {
    const doc = generateVerseAnalysisDoc(analysis, reference);
    const referenceString = reference.startVerse === reference.endVerse 
        ? `${reference.book} ${reference.chapter}-${reference.startVerse}` 
        : `${reference.book} ${reference.chapter}-${reference.startVerse}to${reference.endVerse}`;
    const fileName = `Verse Analysis - ${referenceString}`.replace(/\s/g, '_');
    Packer.toBlob(doc).then(blob => saveBlob(blob, `${fileName}.docx`));
};

// Generates the document structure for a thematic analysis
const generateThematicAnalysisDoc = (analysis: ThematicAnalysis): Document => {
    const { topic, summary, historicalContext, otFoundation, ntFulfillment, keyConcepts, practicalApplication, relatedThemes, keyVerses } = analysis;
    const children: Paragraph[] = [
        new Paragraph({ text: "Biblical Insights AI Thematic Study", heading: HeadingLevel.HEADING_1, alignment: AlignmentType.CENTER }),
        new Paragraph({ text: `Topic: ${topic}`, heading: HeadingLevel.HEADING_2, alignment: AlignmentType.CENTER }),
        
        new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }),
        new Paragraph({ text: "Summary", heading: HeadingLevel.HEADING_2 }),
        new Paragraph({ text: summary, spacing: { after: 240 } }),

        new Paragraph({ text: "Historical & Cultural Context", heading: HeadingLevel.HEADING_2 }),
        new Paragraph({ text: historicalContext, spacing: { after: 240 } }),

        new Paragraph({ text: "Theological Development", heading: HeadingLevel.HEADING_2 }),
        new Paragraph({ text: "Old Testament Foundation", heading: HeadingLevel.HEADING_3 }),
        new Paragraph({ text: otFoundation, spacing: { after: 120 } }),
        new Paragraph({ text: "New Testament Fulfillment", heading: HeadingLevel.HEADING_3 }),
        new Paragraph({ text: ntFulfillment, spacing: { after: 240 } }),
    ];

    if (keyConcepts && keyConcepts.length > 0) {
        children.push(new Paragraph({ text: "Key Theological Concepts", heading: HeadingLevel.HEADING_2 }));
        keyConcepts.forEach(item => {
             children.push(new Paragraph({
                children: [
                    new TextRun({ text: `${item.concept}: `, bold: true }),
                    new TextRun(item.definition),
                ],
                spacing: { after: 120 }
            }));
        });
    }
    
    if (relatedThemes && relatedThemes.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Related Themes", heading: HeadingLevel.HEADING_2 }));
        children.push(new Paragraph({ text: relatedThemes.join(', '), spacing: { after: 240 } }));
    }

    if (practicalApplication && practicalApplication.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Practical Application", heading: HeadingLevel.HEADING_2 }));
        practicalApplication.forEach(point => {
            children.push(new Paragraph({ text: point, bullet: { level: 0 }, spacing: { after: 120 } }));
        });
    }

    if (keyVerses && keyVerses.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Key Verses", heading: HeadingLevel.HEADING_2 }));
        keyVerses.forEach(item => {
            children.push(
                new Paragraph({ text: item.reference, heading: HeadingLevel.HEADING_3 }),
                new Paragraph({ children: [new TextRun({ text: `"${item.verseText}"`, italics: true })], indent: { left: 720 } }),
                new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true }), new TextRun(item.explanation)], spacing: { after: 240 } }),
            );
        });
    }
    
    return new Document({
        styles: documentStyles,
        sections: [{
            footers: { default: defaultFooter },
            children: children,
        }],
    });
};

export const exportThematicAnalysisToDocx = (analysis: ThematicAnalysis) => {
    const doc = generateThematicAnalysisDoc(analysis);
    // Sanitize topic to remove characters that are invalid in filenames
    const safeTopic = analysis.topic.replace(/[\\/:"*?<>|]/g, '');
    const fileName = `Thematic Study - ${safeTopic}`.replace(/\s/g, '_');
    Packer.toBlob(doc).then(blob => saveBlob(blob, `${fileName}.docx`));
};

// Generates the document structure for a Q&A analysis
const generateQaAnalysisDoc = (analysis: QaAnalysis): Document => {
    const { question, answer, historicalContext, theologicalPerspectives, keyConcepts, reflectionPoints, supportingVerses } = analysis;
    const children: Paragraph[] = [
        new Paragraph({ text: "Biblical Insights AI Q&A", heading: HeadingLevel.HEADING_1, alignment: AlignmentType.CENTER }),
        new Paragraph({ text: `Question: ${question}`, heading: HeadingLevel.HEADING_2, alignment: AlignmentType.CENTER }),
        new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }),
        new Paragraph({ text: "Answer", heading: HeadingLevel.HEADING_2 }),
        new Paragraph({ text: answer, spacing: { after: 240 } }),

        new Paragraph({ text: "Historical & Cultural Context", heading: HeadingLevel.HEADING_2 }),
        new Paragraph({ text: historicalContext, spacing: { after: 240 } }),
        
        new Paragraph({ text: "Theological Perspectives", heading: HeadingLevel.HEADING_2 }),
        new Paragraph({ text: theologicalPerspectives, spacing: { after: 240 } }),
    ];

    if (keyConcepts && keyConcepts.length > 0) {
        children.push(new Paragraph({ text: "Key Theological Concepts", heading: HeadingLevel.HEADING_2 }));
        keyConcepts.forEach(item => {
             children.push(new Paragraph({
                children: [
                    new TextRun({ text: `${item.concept}: `, bold: true }),
                    new TextRun(item.definition),
                ],
                spacing: { after: 120 }
            }));
        });
    }

     if (reflectionPoints && reflectionPoints.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Points for Reflection", heading: HeadingLevel.HEADING_2 }));
        reflectionPoints.forEach(point => {
            children.push(
                new Paragraph({ text: point, bullet: { level: 0 }, spacing: { after: 120 } })
            );
        });
    }

    if (supportingVerses && supportingVerses.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Supporting Scripture", heading: HeadingLevel.HEADING_2 }));
        supportingVerses.forEach(item => {
            children.push(
                new Paragraph({ text: item.reference, heading: HeadingLevel.HEADING_3 }),
                new Paragraph({ children: [new TextRun({ text: `"${item.verseText}"`, italics: true })], indent: { left: 720 } }),
                new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true }), new TextRun(item.explanation)], spacing: { after: 240 } }),
            );
        });
    }
    
    return new Document({
        styles: documentStyles,
        sections: [{
            footers: { default: defaultFooter },
            children: children,
        }],
    });
};

export const exportQaAnalysisToDocx = (analysis: QaAnalysis) => {
    const doc = generateQaAnalysisDoc(analysis);
    // Sanitize question part to remove characters that are invalid in filenames
    const safeQuestionPart = analysis.question.substring(0, 30).replace(/[\\/:"*?<>|]/g, '');
    const fileName = `Q&A - ${safeQuestionPart}`.replace(/\s/g, '_');
    Packer.toBlob(doc).then(blob => saveBlob(blob, `${fileName}.docx`));
};

const generateEventAnalysisDoc = (analysis: EventAnalysis): Document => {
    const { title, passageReference, passageText, summary, charactersAndSymbolism, primaryMessage, secondaryThemes, historicalContext, originalAudienceInterpretation, reflectionPoints, keyWordAnalysis, relatedVerses } = analysis;
    const children: (Paragraph | Table)[] = [
        new Paragraph({ text: "Biblical Insights AI Event Study", heading: HeadingLevel.HEADING_1, alignment: AlignmentType.CENTER }),
        new Paragraph({ text: title, heading: HeadingLevel.HEADING_2, alignment: AlignmentType.CENTER }),
        new Paragraph({ text: passageReference, heading: HeadingLevel.HEADING_3, alignment: AlignmentType.CENTER }),
        
        new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }),
        new Paragraph({ text: "Passage Text (KJV)", heading: HeadingLevel.HEADING_2 }),
        new Paragraph({ children: [new TextRun({ text: `"${passageText}"`, italics: true })], spacing: { after: 240 } }),

        new Paragraph({ text: "Summary", heading: HeadingLevel.HEADING_2 }),
        new Paragraph({ text: summary, spacing: { after: 240 } }),

        new Paragraph({ text: "Characters & Symbolism", heading: HeadingLevel.HEADING_2 }),
        ...charactersAndSymbolism.map(item => new Paragraph({
            children: [
                new TextRun({ text: `${item.name}: `, bold: true }),
                new TextRun(item.description),
            ],
            spacing: { after: 120 }
        })),

        new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }),
    ];
    
    children.push(new Paragraph({ text: "Theological Message", heading: HeadingLevel.HEADING_2 }));
    children.push(new Paragraph({ text: "Primary Message", heading: HeadingLevel.HEADING_3 }));
    children.push(new Paragraph({ text: primaryMessage, spacing: { after: 120 } }));
    if (secondaryThemes && secondaryThemes.length > 0) {
        children.push(new Paragraph({ text: "Secondary Themes", heading: HeadingLevel.HEADING_3 }));
        children.push(new Paragraph({ text: secondaryThemes.join(', '), spacing: { after: 240 } }));
    }

    children.push(new Paragraph({ text: "Historical & Cultural Context", heading: HeadingLevel.HEADING_2 }));
    children.push(new Paragraph({ text: historicalContext, spacing: { after: 240 } }));

    children.push(new Paragraph({ text: "Original Audience Interpretation", heading: HeadingLevel.HEADING_2 }));
    children.push(new Paragraph({ text: originalAudienceInterpretation, spacing: { after: 240 } }));

    if (keyWordAnalysis && keyWordAnalysis.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Key Word Analysis", heading: HeadingLevel.HEADING_2 }));
        keyWordAnalysis.forEach(word => {
            children.push(
                new Paragraph({
                    children: [new TextRun({ text: word.word, bold: true, size: 28 })],
                    spacing: { after: 120, before: 240 }
                }),
                new Paragraph({
                    children: [
                        new TextRun({ text: "Original: ", bold: true }),
                        new TextRun({ text: `${word.original} (` }),
                        new TextRun({ text: word.transliteration, italics: true }),
                        new TextRun({ text: ")" }),
                    ],
                    bullet: { level: 0 },
                    indent: { left: 720 },
                    spacing: { after: 60 }
                }),
                new Paragraph({
                    children: [
                        new TextRun({ text: "Strong's: ", bold: true }),
                        new TextRun(word.strongs),
                    ],
                    bullet: { level: 0 },
                    indent: { left: 720 },
                    spacing: { after: 60 }
                }),
                new Paragraph({
                    children: [
                        new TextRun({ text: "Grammar: ", bold: true }),
                        new TextRun(word.grammar),
                    ],
                    bullet: { level: 0 },
                    indent: { left: 720 },
                    spacing: { after: 60 }
                }),
                new Paragraph({
                    children: [
                        new TextRun({ text: "Meaning: ", bold: true }),
                        new TextRun(word.meaning),
                    ],
                    bullet: { level: 0 },
                    indent: { left: 720 },
                    spacing: { after: 60 }
                }),
            );
        });
    }

    if (relatedVerses && relatedVerses.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Related Verses", heading: HeadingLevel.HEADING_2 }));
        relatedVerses.forEach(item => {
            children.push(
                new Paragraph({ text: item.reference, heading: HeadingLevel.HEADING_3 }),
                new Paragraph({ children: [new TextRun({ text: `"${item.verseText}"`, italics: true })], indent: { left: 720 } }),
                new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true }), new TextRun(item.explanation)], spacing: { after: 240 } }),
            );
        });
    }

    if (reflectionPoints && reflectionPoints.length > 0) {
        children.push(new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }));
        children.push(new Paragraph({ text: "Points for Reflection", heading: HeadingLevel.HEADING_2 }));
        reflectionPoints.forEach(point => {
            children.push(new Paragraph({ text: point, bullet: { level: 0 }, spacing: { after: 120 } }));
        });
    }
    
    return new Document({
        styles: documentStyles,
        sections: [{
            footers: { default: defaultFooter },
            children: children,
        }],
    });
};

export const exportEventAnalysisToDocx = (analysis: EventAnalysis) => {
    const doc = generateEventAnalysisDoc(analysis);
    // Sanitize title to remove characters that are invalid in filenames
    const safeTitle = analysis.title.replace(/[\\/:"*?<>|]/g, '');
    const fileName = `Event Analysis - ${safeTitle}`.replace(/\s/g, '_');
    Packer.toBlob(doc).then(blob => saveBlob(blob, `${fileName}.docx`));
};

const generateSystematicAnalysisDoc = (analysis: SystematicAnalysis): Document => {
    const { level, introduction, sessions } = analysis;
    const children: Paragraph[] = [
        new Paragraph({ text: "Biblical Insights AI", heading: HeadingLevel.HEADING_1, alignment: AlignmentType.CENTER }),
        new Paragraph({ text: `Systematic Study: ${level}`, heading: HeadingLevel.HEADING_2, alignment: AlignmentType.CENTER }),
        new Paragraph({ thematicBreak: true, spacing: { before: 240, after: 240 } }),
        new Paragraph({ text: "Introduction", heading: HeadingLevel.HEADING_2 }),
        new Paragraph({ text: introduction, spacing: { after: 240 } }),
    ];

    sessions.forEach(session => {
        children.push(new Paragraph({ text: `Session ${session.session}: ${session.title}`, heading: HeadingLevel.HEADING_2, spacing: { before: 240 } }));
        children.push(new Paragraph({ children: [new TextRun({ text: session.introduction, italics: true })], spacing: { after: 240 } }));
        
        session.steps.forEach(step => {
            children.push(new Paragraph({ text: `Step ${step.step}: ${step.topic}`, heading: HeadingLevel.HEADING_3, spacing: { before: 120 } }));
            
            children.push(new Paragraph({ children: [new TextRun({ text: "Explanation", bold: true })] }));
            children.push(new Paragraph({ text: step.explanation, spacing: { after: 120 } }));
            
            if (step.keyConcepts && step.keyConcepts.length > 0) {
                 children.push(new Paragraph({ children: [new TextRun({ text: "Key Concepts", bold: true })], spacing: { before: 120 } }));
                 step.keyConcepts.forEach(kc => {
                     children.push(new Paragraph({
                         children: [new TextRun({ text: `${kc.concept}: `, bold: true }), new TextRun(kc.definition)],
                         bullet: { level: 0 },
                         spacing: { after: 60 }
                     }));
                 });
            }

            if (step.commonMisconceptions && step.commonMisconceptions.length > 0) {
                 children.push(new Paragraph({ children: [new TextRun({ text: "Common Misconceptions", bold: true })], spacing: { before: 120 } }));
                 step.commonMisconceptions.forEach(cm => {
                     children.push(new Paragraph({
                         children: [
                             new TextRun({ text: `Misconception: `, bold: true }),
                             new TextRun({ text: cm.misconception, italics: true }),
                         ],
                         bullet: { level: 0 },
                         spacing: { after: 60 }
                     }));
                     children.push(new Paragraph({
                         children: [
                             new TextRun({ text: `Correction: `, bold: true }),
                             new TextRun(cm.correction),
                         ],
                         indent: { left: 720 },
                         spacing: { after: 60 }
                     }));
                 });
            }
            
            if (step.historicalDevelopment) {
                children.push(new Paragraph({ children: [new TextRun({ text: "Historical Development", bold: true })], spacing: { before: 120 } }));
                children.push(new Paragraph({ text: step.historicalDevelopment }));
            }
            
            children.push(new Paragraph({ children: [new TextRun({ text: "Key Verses", bold: true })], spacing: { before: 240 } }));
            step.keyVerses.forEach(verse => {
                children.push(
                    new Paragraph({ children: [new TextRun({ text: verse.reference, bold: true })], spacing: { before: 120 } }),
                    new Paragraph({ children: [new TextRun({ text: `"${verse.verseText}"`, italics: true })], indent: { left: 720 } }),
                    new Paragraph({ children: [new TextRun({ text: "Relevance: ", bold: true }), new TextRun(verse.explanation)], spacing: { after: 120 } }),
                );
            });

            if(step.reflectionQuestions && step.reflectionQuestions.length > 0) {
                children.push(new Paragraph({ children: [new TextRun({ text: "Reflection Questions", bold: true })], spacing: { before: 120 } }));
                step.reflectionQuestions.forEach(q => {
                    children.push(new Paragraph({ text: q, bullet: { level: 0 }, spacing: { after: 60 } }));
                });
            }
            
            children.push(new Paragraph({ children: [new TextRun({ text: "Next Step: ", bold: true, italics: true }), new TextRun({ text: step.nextStepSuggestion, italics: true })], spacing: { after: 240 } }));
        });
    });

    return new Document({
        styles: documentStyles,
        sections: [{
            footers: { default: defaultFooter },
            children: children,
        }],
    });
};

export const exportSystematicAnalysisToDocx = (analysis: SystematicAnalysis) => {
    const doc = generateSystematicAnalysisDoc(analysis);
    const fileName = `Systematic_Study_${analysis.level}`;
    Packer.toBlob(doc).then(blob => saveBlob(blob, `${fileName}.docx`));
};